// <auto-generated />
using System;
using LeadManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107005437_FullSeed")]
    partial class FullSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeadManager.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leads", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Eletricista",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Instalações elétricas residenciais.",
                            Email = "joao.silva@email.com",
                            FirstName = "João",
                            LastName = "Silva",
                            Phone = "11999999999",
                            Price = 800m,
                            Status = "invited",
                            Suburb = "São Paulo"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Pintora",
                            DateCreated = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pintura residencial e comercial.",
                            Email = "maria.souza@email.com",
                            FirstName = "Maria",
                            LastName = "Souza",
                            Phone = "11988888888",
                            Price = 450m,
                            Status = "invited",
                            Suburb = "Campinas"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Encanador",
                            DateCreated = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reparo e instalação hidráulica.",
                            Email = "carlos.lima@email.com",
                            FirstName = "Carlos",
                            LastName = "Lima",
                            Phone = "11977777777",
                            Price = 1200m,
                            Status = "accepted",
                            Suburb = "Santos"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Jardineira",
                            DateCreated = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Serviços de jardinagem e paisagismo.",
                            Email = "fernanda.oliveira@email.com",
                            FirstName = "Fernanda",
                            LastName = "Oliveira",
                            Phone = "11966666666",
                            Price = 300m,
                            Status = "invited",
                            Suburb = "São Paulo"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Marceneiro",
                            DateCreated = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Móveis planejados sob medida.",
                            Email = "rafael.costa@email.com",
                            FirstName = "Rafael",
                            LastName = "Costa",
                            Phone = "11955555555",
                            Price = 950m,
                            Status = "invited",
                            Suburb = "Guarulhos"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Diarista",
                            DateCreated = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Limpeza residencial e comercial.",
                            Email = "patricia.ferreira@email.com",
                            FirstName = "Patrícia",
                            LastName = "Ferreira",
                            Phone = "11944444444",
                            Price = 250m,
                            Status = "invited",
                            Suburb = "Santo André"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Pedreiro",
                            DateCreated = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reformas e construções gerais.",
                            Email = "diego.mendes@email.com",
                            FirstName = "Diego",
                            LastName = "Mendes",
                            Phone = "11933333333",
                            Price = 1100m,
                            Status = "invited",
                            Suburb = "Osasco"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Decoradora",
                            DateCreated = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Design de interiores e consultoria de ambientes.",
                            Email = "aline.pereira@email.com",
                            FirstName = "Aline",
                            LastName = "Pereira",
                            Phone = "11922222222",
                            Price = 600m,
                            Status = "invited",
                            Suburb = "Barueri"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Técnico em Ar Condicionado",
                            DateCreated = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Instalação e manutenção de ar-condicionado.",
                            Email = "fabio.nunes@email.com",
                            FirstName = "Fábio",
                            LastName = "Nunes",
                            Phone = "11911111111",
                            Price = 500m,
                            Status = "invited",
                            Suburb = "São Caetano"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Faxineira",
                            DateCreated = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Serviços de faxina e limpeza rápida.",
                            Email = "camila.rodrigues@email.com",
                            FirstName = "Camila",
                            LastName = "Rodrigues",
                            Phone = "11900000000",
                            Price = 200m,
                            Status = "invited",
                            Suburb = "Diadema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
