// <auto-generated />
using System;
using LeadManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106233659_UpdateLeadEntityAndSeed")]
    partial class UpdateLeadEntityAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeadManager.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leads", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Eletricista",
                            DateCreated = new DateTime(2025, 11, 6, 23, 36, 58, 216, DateTimeKind.Utc).AddTicks(8169),
                            Description = "Instalações e manutenções elétricas residenciais.",
                            Email = "joao.silva@email.com",
                            FirstName = "João",
                            LastName = "Silva",
                            Phone = "11999999999",
                            Price = 800m,
                            Status = "invited",
                            Suburb = "São Paulo"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Pintora",
                            DateCreated = new DateTime(2025, 11, 6, 23, 36, 58, 216, DateTimeKind.Utc).AddTicks(9214),
                            Description = "Serviços de pintura residencial e comercial.",
                            Email = "maria.souza@email.com",
                            FirstName = "Maria",
                            LastName = "Souza",
                            Phone = "11988888888",
                            Price = 450m,
                            Status = "invited",
                            Suburb = "Campinas"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Encanador",
                            DateCreated = new DateTime(2025, 11, 6, 23, 36, 58, 216, DateTimeKind.Utc).AddTicks(9598),
                            Description = "Reparo e instalação hidráulica completa.",
                            DiscountedPrice = 1080m,
                            Email = "carlos.lima@email.com",
                            FirstName = "Carlos",
                            LastName = "Lima",
                            Phone = "11977777777",
                            Price = 1200m,
                            Status = "accepted",
                            Suburb = "Santos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
